name: Build DLL

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Link WinRT Libraries
        shell: powershell
        run: |
          Add-Content -Path "dllmain.cpp" -Value "`n#pragma comment(lib, `"windowsapp.lib`")`n#pragma comment(lib, `"runtimeobject.lib`")"

      - name: Build
        run: msbuild PrismTextureStreamerFB.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: PrismTextureStreamerFB-DLL
          path: x64/Release/*.dll
